[package]
name = "dstts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tts_rust = "0.3.5"
rodio = "0.17.3"
tokio = { version = "1.0", features = ["full"] }
serenity = "0.10"
serde_json = "1.0"
